repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
  - id: go-fmt
  - id: go-mod-tidy
- repo: https://github.com/google/yamlfmt
  rev: v0.10.0
  hooks:
  - id: yamlfmt
    exclude: ^deployment/mcad-controller|config/crd/bases/.*\.yaml|config/rbac/role\.yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: hack/boilerplate.go.txt
  - id: mixed-line-ending
    args: ["--fix=lf"]
