apiVersion: workload.codeflare.dev/v1beta1
kind: AppWrapper
metadata:
  name: appwrapper-sample
spec:
  priority: 5
  schedulingSpec:
    minAvailable: 2
    requeuing:
      maxNumRequeuings: 5
    clusterScheduling:
      policyResult:
        targetCluster:
          name: self
  resources:
    GenericItems:
    - custompodresources:
      - requests:
          nvidia.com/gpu: 8
        replicas: 1
      generictemplate:
        apiVersion: v1
        kind: Pod
        metadata:
          namespace: <APPWRAPPER_NAMESPACE>
          name: <APPWRAPPER_NAME>-1
          labels:
            workload.codeflare.dev/namespace: <APPWRAPPER_NAMESPACE>
            workload.codeflare.dev: <APPWRAPPER_NAME>
        spec:
          restartPolicy: Never
          containers:
            - name: busybox
              image: busybox
              command: ["sh", "-c", "sleep 5"]
              resources:
                requests:
                  nvidia.com/gpu: 8
                limits:
                  nvidia.com/gpu: 8
    - custompodresources:
      - requests:
          nvidia.com/gpu: 4
        replicas: 1
      generictemplate:
        apiVersion: v1
        kind: Pod
        metadata:
          namespace: <APPWRAPPER_NAMESPACE>
          name: <APPWRAPPER_NAME>-2
          labels:
            workload.codeflare.dev/namespace: <APPWRAPPER_NAMESPACE>
            workload.codeflare.dev: <APPWRAPPER_NAME>
        spec:
          restartPolicy: Never
          containers:
            - name: busybox
              image: busybox
              command: ["sh", "-c", "sleep 10"]
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
