apiVersion: workload.codeflare.dev/v1alpha1
kind: BoxedJob
metadata:
  name: test
  annotations:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  suspend: true
  components:
  - podSets:
    - replicas: 2
      path: template.spec.template
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: test
        labels:
          app: test
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: test
        template:
          metadata:
            labels:
              app: test
              workload.codeflare.dev/boxedjob: sample
          spec:
            terminationGracePeriodSeconds: 0
            containers:
            - name: busybox
              image: quay.io/project-codeflare/busybox:1.36
              command: ["sh", "-c", "sleep 10000"]
              resources:
                requests:
                  cpu: 2
