apiVersion: workload.codeflare.dev/v1alpha1
kind: BoxedJob
metadata:
  name: sample
  annotations:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  components:
  - topology:
    - count: 1
      requests:
        cpu: 1
    spec:
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          workload.codeflare.dev/boxedjob: sample
        name: sample
      spec:
        restartPolicy: Never
        containers:
        - name: busybox
          image: quay.io/project-codeflare/busybox:1.36
          command: ["sh", "-c", "sleep 5"]
          resources:
            requests:
              cpu: 1
