# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 1 worker node
nodes:
# the control plane node config
- role: control-plane
  # kubernetes version 1.26.14 from kind v0.22.0
  image: kindest/node:v1.26.14@sha256:5d548739ddef37b9318c70cb977f57bf3e5015e4552be4e27e57280a8cbb8e4f
# the worker
- role: worker
  # kubernetes version 1.26.14 from kind v0.22.0
  image: kindest/node:v1.26.14@sha256:5d548739ddef37b9318c70cb977f57bf3e5015e4552be4e27e57280a8cbb8e4f
