apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: clusterconfig
    app.kubernetes.io/created-by: mcad
    app.kubernetes.io/part-of: mcad
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: workload.codeflare.dev/v1beta1
kind: ClusterInfo
metadata:
  name: cluster
  namespace: system
  labels:
    app.kubernetes.io/name: clusterinfo
    app.kubernetes.io/instance: cluster
    app.kubernetes.io/component: clusterconfig
    app.kubernetes.io/created-by: mcad
    app.kubernetes.io/part-of: mcad
    app.kubernetes.io/managed-by: kustomize
spec:
