{{- if not (or (eq .Values.deploymentMode "runner") (eq .Values.deploymentMode "kueue") )}}
apiVersion: workload.codeflare.dev/v1beta1
kind: ClusterInfo
metadata:
  name: {{ .Values.clusterName }}
spec:
{{- end }}
