# This workflow will build MCAD Kueue extensions and run unit test and E2E tests
name: MCAD-CI
on:
  pull_request:
    branches:
    - 'main'
    - 'release-*'

jobs:
  MCAD-Kueue-CI:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        ref: "refs/pull/${{ github.event.number }}/merge"
        fetch-depth: 0

    - name: Set latest tag and Branch name
      run: |
        BRANCH=${{ github.event.pull_request.head.ref }}
        echo "GIT_BRANCH=$(echo "$BRANCH" | sed 's/[^A-Za-z0-9._-]/-/g' )" >> $GITHUB_ENV
        echo "TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'

    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Run pre-commit checks
      uses: pre-commit/action@v3.0.0

    - name: Build
      run: make build

    - name: Build Image
      run: |
        make docker-build -e GIT_BRANCH=${{ env.GIT_BRANCH }} TAG=${{ env.GIT_BRANCH }}-${{ env.TAG }}

    - name: Create cluster and deploy Kueue
      run: |
        ./hack/create-test-cluster.sh
        ./hack/deploy-kueue.sh

    - name: Deploy MCAD Kueue extensions
      run: |
        echo "TODO! implement this"

    - name: Run E2E tests
      run: |
        echo "TODO! implement this"
