# This workflow will build MCAD Kueue extensions and run unit test and E2E tests
name: MCAD-KUEUE-CI
on:
  push:
    branches: [main]
  pull_request:
    branches:
    - 'main'
    - 'release-*'

jobs:
  MCAD-Kueue-CI:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set latest tag and Branch name
      run: |
        echo "GIT_BRANCH=gha-ci" >> $GITHUB_ENV
        echo "TAG=$GITHUB_RUN_ID" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run pre-commit checks
      uses: pre-commit/action@v3.0.0

    - name: Build
      run: make build

    - name: Build Image
      run: |
        make docker-build -e GIT_BRANCH=${{ env.GIT_BRANCH }} TAG=${{ env.GIT_BRANCH }}-${{ env.TAG }}

    - name: Create and configure cluster
      run: ./hack/create-test-cluster.sh

    - name: Deploy Kueue
      run: ./hack/deploy-kueue.sh

    - name: Deploy MCAD Kueue extensions
      env:
        MCAD_DEPLOYMENT_MODE: "kueue"
      run: |
        make kind-push helm-install-existing-images -e GIT_BRANCH=${{ env.GIT_BRANCH }} TAG=${{ env.GIT_BRANCH }}-${{ env.TAG }}

    - name: Run E2E tests
      run: ./hack/run-kueue-tests-on-cluster.sh
